# Generated by Django 5.0.6 on 2024-11-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ropaLavanderiaExterna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limpio", models.IntegerField()),
                ("suciio", models.IntegerField()),
                ("cantidad", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ropaLavanderiaHospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limpio", models.IntegerField()),
                ("suciio", models.IntegerField()),
                ("cantidad", models.IntegerField()),
            ],
        ),
    ]
